
'use server';

/**
 * @fileOverview A Genkit flow for generating a cartoonish image for a lesson.
 *
 * - generateLessonImage - A function that takes a prompt and returns an image.
 * - GenerateLessonImageInput - The input type for the function.
 * - GenerateLessonImageOutput - The return type for the function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';
import { withRetry, isRetryableGoogleAIError } from '@/lib/retry';

const GenerateLessonImageInputSchema = z.string().describe('A short text prompt describing the desired image.');
export type GenerateLessonImageInput = z.infer<typeof GenerateLessonImageInputSchema>;

const GenerateLessonImageOutputSchema = z.object({
  imageDataUri: z.string().describe("The generated image as a data URI. 'data:image/png;base64,<encoded_data>'"),
});
export type GenerateLessonImageOutput = z.infer<typeof GenerateLessonImageOutputSchema>;

export async function generateLessonImage(input: GenerateLessonImageInput): Promise<GenerateLessonImageOutput> {
  return generateLessonImageFlow(input);
}

const generateLessonImageFlow = ai.defineFlow(
  {
    name: 'generateLessonImageFlow',
    inputSchema: GenerateLessonImageInputSchema,
    outputSchema: GenerateLessonImageOutputSchema,
  },
  async (prompt) => {
    // Check if the prompt is for a chart/graph or a cartoonish illustration
    const isChartPrompt = /chart|graph|diagram|table|illustrates|showing/i.test(prompt);

    const fullPrompt = isChartPrompt
      ? `Generate a data visualization for the following IELTS Writing Task 1 prompt. The visualization should be a clean, clear, and simple chart, graph, or diagram. The style must be minimalist, easy to read, with clear labels but no overly complex details, suitable for a textbook.
      
      Prompt: "${prompt}"`
      : `A cute, cartoonish, simple, minimalist, doodle-style illustration that literally depicts the following scene: "${prompt}". The style should have clean lines and a friendly feel, suitable for an educational app.`;

    const { media } = await withRetry(() => ai.generate({
      model: 'googleai/gemini-2.5-flash-image-preview',
      prompt: fullPrompt,
      config: {
        responseModalities: ['IMAGE'],
        temperature: 0.2, // Lower temperature for less randomness and more literal interpretation
      },
    }), {
        retryOn: isRetryableGoogleAIError
    });
    
    if (!media?.url) {
      throw new Error('No image media was generated by the model.');
    }
    
    // The model already returns a base64 data URI, so we can use it directly.
    return {
      imageDataUri: media.url,
    };
  }
);
