'use server';

/**
 * @fileOverview A dedicated Genkit flow for generating a data visualization image
 * (chart, graph, diagram) for an IELTS Writing Task 1 prompt.
 *
 * - generateWritingTaskImage - A function that takes a prompt and returns an image.
 * - GenerateWritingTaskImageInput - The input type for the function.
 * - GenerateWritingTaskImageOutput - The return type for the function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';
import { withRetry, isRetryableGoogleAIError } from '@/lib/retry';

const GenerateWritingTaskImageInputSchema = z.string().describe('The full text prompt of the IELTS Writing Task 1 question.');
export type GenerateWritingTaskImageInput = z.infer<typeof GenerateWritingTaskImageInputSchema>;

const GenerateWritingTaskImageOutputSchema = z.object({
  imageDataUri: z.string().describe("The generated image as a data URI. 'data:image/png;base64,<encoded_data>'"),
});
export type GenerateWritingTaskImageOutput = z.infer<typeof GenerateWritingTaskImageOutputSchema>;

export async function generateWritingTaskImage(input: GenerateWritingTaskImageInput): Promise<GenerateWritingTaskImageOutput> {
  return generateWritingTaskImageFlow(input);
}

const generateWritingTaskImageFlow = ai.defineFlow(
  {
    name: 'generateWritingTaskImageFlow',
    inputSchema: GenerateWritingTaskImageInputSchema,
    outputSchema: GenerateWritingTaskImageOutputSchema,
  },
  async (prompt) => {
    // This prompt is highly specific to creating relevant data visualizations.
    const fullPrompt = `You are a data visualization expert creating a graphic for an IELTS Writing Task 1 prompt. Generate a clean, clear, and simple chart, graph, or diagram that accurately represents the data described in the following prompt. The style must be minimalist, easy to read, with clear labels but no overly complex details, suitable for a textbook.
      
      IELTS Prompt: "${prompt}"`;

    const { media } = await withRetry(() => ai.generate({
      model: 'googleai/gemini-2.5-flash-image-preview',
      prompt: fullPrompt,
      config: {
        responseModalities: ['IMAGE'],
      }
    }), {
        retryOn: isRetryableGoogleAIError
    });
    
    if (!media?.url) {
      throw new Error('No image media was generated by the model for the writing task.');
    }
    
    // The model already returns a base64 data URI, so we can use it directly.
    return {
      imageDataUri: media.url,
    };
  }
);
